on:
  push:
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install    
        working-directory: ./frontend

      - name: Generate build
        run: npm run build
        working-directory: ./frontend

      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v2
        with:
          name: ict2x01-frontend-build
          path: ./frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get artifact from build
        uses: actions/download-artifact@v2
        with:
          name: ict2x01-frontend-build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
